package com.programmer.gate.model;
// Generated May 20, 2018 3:10:55 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * St001 generated by hbm2java
 */
@Entity
@Table(name="ST001"
    ,schema="GLIB"
)
public class St001  implements java.io.Serializable {


     private double id;
     private String code;
     private String defination;
     private Date entryDate;
     private BigDecimal entryUser;
     private String name;
     private String updateDate;

    public St001() {
    }

	
    public St001(double id) {
        this.id = id;
    }
    public St001(double id, String code, String defination, Date entryDate, BigDecimal entryUser, String name, String updateDate) {
       this.id = id;
       this.code = code;
       this.defination = defination;
       this.entryDate = entryDate;
       this.entryUser = entryUser;
       this.name = name;
       this.updateDate = updateDate;
    }
   
    @Id 
    @Column(name="ID", unique=true, nullable=false, precision=126, scale=0)
    public double getId() {
        return this.id;
    }
    
    public void setId(double id) {
        this.id = id;
    }

    
    @Column(name="CODE", length=16)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="DEFINATION", length=200)
    public String getDefination() {
        return this.defination;
    }
    
    public void setDefination(String defination) {
        this.defination = defination;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE", length=7)
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    
    @Column(name="ENTRY_USER", precision=22, scale=0)
    public BigDecimal getEntryUser() {
        return this.entryUser;
    }
    
    public void setEntryUser(BigDecimal entryUser) {
        this.entryUser = entryUser;
    }

    
    @Column(name="NAME", length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="UPDATE_DATE", length=80)
    public String getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }




}


