package com.programmer.gate.model;
// Generated May 21, 2018 10:56:57 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Us002Id generated by hbm2java
 */
@Embeddable
public class Us002Id  implements java.io.Serializable {


     private double id;
     private double roleId;

    public Us002Id() {
    }

    public Us002Id(double id, double roleId) {
       this.id = id;
       this.roleId = roleId;
    }
   


    @Column(name="ID", nullable=false, precision=126, scale=0)
    public double getId() {
        return this.id;
    }
    
    public void setId(double id) {
        this.id = id;
    }


    @Column(name="ROLE_ID", nullable=false, precision=126, scale=0)
    public double getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(double roleId) {
        this.roleId = roleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Us002Id) ) return false;
		 Us002Id castOther = ( Us002Id ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getRoleId()==castOther.getRoleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getId();
         result = 37 * result + (int) this.getRoleId();
         return result;
   }   


}


