package com.programmer.gate.model;
// Generated May 20, 2018 3:10:55 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Us001 generated by hbm2java
 */
@Entity
@Table(name="US001"
    ,schema="GLIB"
)
public class Us001  implements java.io.Serializable {


     private double id;
     private String code;
     private String entryDate;
     private String role;
     private BigDecimal statusId;
     private Date updateDate;
     private BigDecimal updateUser;
     private Set<Us002> us002s = new HashSet<Us002>(0);

    public Us001() {
    }

	
    public Us001(double id) {
        this.id = id;
    }
    public Us001(double id, String code, String entryDate, String role, BigDecimal statusId, Date updateDate, BigDecimal updateUser, Set<Us002> us002s) {
       this.id = id;
       this.code = code;
       this.entryDate = entryDate;
       this.role = role;
       this.statusId = statusId;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.us002s = us002s;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=126, scale=0)
    public double getId() {
        return this.id;
    }
    
    public void setId(double id) {
        this.id = id;
    }

    
    @Column(name="CODE", length=16)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="ENTRY_DATE", length=80)
    public String getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate;
    }

    
    @Column(name="ROLE", length=80)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="STATUS_ID", precision=22, scale=0)
    public BigDecimal getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(BigDecimal statusId) {
        this.statusId = statusId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", precision=22, scale=0)
    public BigDecimal getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(BigDecimal updateUser) {
        this.updateUser = updateUser;
    }
    
    
    //@JsonIgnore
    //@JsonBackReference
    //@JsonManagedReference
    @OneToMany(fetch=FetchType.LAZY, mappedBy="us001")
    public Set<Us002> getUs002s() {
        return this.us002s;
    }
    
    public void setUs002s(Set<Us002> us002s) {
        this.us002s = us002s;
    }




}


