package com.programmer.gate.model;
// Generated May 22, 2018 3:27:56 PM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Us002 generated by hbm2java
 */
@Entity
@Table(name="US002"
    ,schema="GLIB"
    , uniqueConstraints = @UniqueConstraint(columnNames="CONTACT_NO") 
)
public class Us002  implements java.io.Serializable {


     private int id;
     private Us001 us001;
     private String firstName;
     private String lastName;
     private String contactNo;
     private String EMail;
     private String password;
     private int statusId;
     private String entryDate;
     private Date updateDate;

    public Us002() {
    }

	
    public Us002(int id) {
        this.id = id;
    }
    public Us002(int id, Us001 us001, String firstName, String lastName, String contactNo, String EMail, String password, int statusId, String entryDate, Date updateDate) {
       this.id = id;
       this.us001 = us001;
       this.firstName = firstName;
       this.lastName = lastName;
       this.contactNo = contactNo;
       this.EMail = EMail;
       this.password = password;
       this.statusId = statusId;
       this.entryDate = entryDate;
       this.updateDate = updateDate;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @JsonIgnore
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ROLE_ID")
    public Us001 getUs001() {
        return this.us001;
    }
    
    public void setUs001(Us001 us001) {
        this.us001 = us001;
    }

    
    @Column(name="FIRST_NAME", length=20)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LAST_NAME", length=20)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="CONTACT_NO", unique=true, length=20)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    
    @Column(name="E_MAIL", length=30)
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }

    
    @Column(name="PASSWORD", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="STATUS_ID", precision=22, scale=0)
    public int getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }

    
    @Column(name="ENTRY_DATE", length=20)
    public String getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


