package com.programmer.gate.model;
// Generated May 22, 2018 3:27:56 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Us001 generated by hbm2java
 */
@Entity
@Table(name="US001"
    ,schema="GLIB"
)
public class Us001  implements java.io.Serializable {


     private int id;
     private String code;
     private String role;
     private int statusId;
     private Date entryDate;
     private Date updateDate;
     private int updateUser;
     private Set<Us002> us002s = new HashSet<Us002>(0);

    public Us001() {
    }

	
    public Us001(int id) {
        this.id = id;
    }
    public Us001(int id, String code, String role, int statusId, Date entryDate, Date updateDate, int updateUser, Set<Us002> us002s) {
       this.id = id;
       this.code = code;
       this.role = role;
       this.statusId = statusId;
       this.entryDate = entryDate;
       this.updateDate = updateDate;
       this.updateUser = updateUser;
       this.us002s = us002s;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="CODE", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="ROLE", length=20)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="STATUS_ID", precision=22, scale=0)
    public int getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE", length=7)
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATE", length=7)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="UPDATE_USER", precision=22, scale=0)
    public int getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(int updateUser) {
        this.updateUser = updateUser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="us001")
    public Set<Us002> getUs002s() {
        return this.us002s;
    }
    
    public void setUs002s(Set<Us002> us002s) {
        this.us002s = us002s;
    }




}


